LaptrinhWWW_BaiTapLonWWW_Nhom08/UI.Web/Models/JournalistViewmodel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UI.Web.Models
{
    public class JournalistViewmodel
    {
       
        public int UserId { get; set; }
        [DisplayName("Tên nhà báo")]
        [RegularExpression(@"^([A-Z][a-z]{1,7})(\s([A-Z][a-z]{1,7}){1,7})+$", ErrorMessage = "Vui lòng không để trống tên thành viên")]
        public string UserName { get; set; }
        [DisplayName("Địa chỉ email")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Vui lòng nhập đúng định dạng email")]
        public string Email { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        [DisplayName("Năm sinh")]
        public DateTime DateOfBirth { get; set; }
        [DisplayName("Giới tính")]
        public int Gender { get; set; }
        public int Role { get; set; }
        [DisplayName("Số điện thoại")]
        [DataType(DataType.PhoneNumber, ErrorMessage = "Vui lòng nhập đúng định dạng số điện thoại")]
        public string Phone { get; set; }
        [DisplayName("Tên đăng nhập")]
        public string AccountName { get; set; }
        [DisplayName("Mật khẩu")]
        public string Password { get; set; }
        public int Active { get; set; }
    }
}

LaptrinhWWW_BaiTapLonWWW_Nhom08/UI.Web/Controllers/JournalistController.cs
using EntityFrameworks.Model;
using Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UI.Web.Models;

namespace UI.Web.Controllers
{
    public class JournalistController : Controller
    {
        private NewspaperService _newsService;
        // GET: Journalist
        private UserService _userService;
        private AccountService _accountService;
        public JournalistController()
        {
            _newsService = new NewspaperService();
            _userService = new UserService();
            _accountService = new AccountService();
        }
        public ActionResult Index()
        {
            if (UI.Web.Controllers.SharedController.Role == 3)
            {
                var list = _userService.ListJournalist(2);
                return View(list);
            }
            else
            {
                return View();
            }
        }
        public ActionResult AddJournalist()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddJournalist(JournalistViewmodel journalist)
        {
            User user = new User();
            Account account = new Account();
            user.UserId = journalist.UserId;
            user.UserName = journalist.UserName;
            user.Email = journalist.Email;
            user.DateOfBirth = journalist.DateOfBirth;
            user.Gender = journalist.Gender;
            user.Role = 2;
            user.Phone = journalist.Phone;

            
            try
            {
                var temp = _userService.AddUser(user);
                if (temp != null)
                {
                    account.AccountName = journalist.AccountName;
                    account.Password = journalist.Password;
                    account.UserId = temp.UserId;
                    account.Active = 1;
                    var acc = _accountService.AddAccount(account);
                    if (acc != null)
                        return View("Index");
                }
            }catch(Exception)
            {
                return View("AddJournalist");
            }
            return View("AddJournalist");
        }

        public ActionResult Edit(int id)
        {
            User user = _userService.GetJournalist(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }
        [HttpPost]
        public ActionResult Edit(User s)
        {
            // List<User> users = new List<User>();
            // User temp = _userService.GetJournalist(s.UserId);
            if (s != null)
            {
                //temp.UserName = s.UserName;
                //temp.Email = s.Email;
                //temp.DateOfBirth = s.DateOfBirth;
                //temp.Gender = s.Gender;
                //temp.Role = 2;
                //temp.Phone = s.Phone;
                _userService.UpdateUser(s);
                return RedirectToAction("Index");
            }
            return View(s);
        }

        public ActionResult DeleteJournalist(int id)
        {
            User s = _userService.GetJournalist(id);
            if (s == null)
            {
                return HttpNotFound();
            }
            return View(s);
        }
        public ActionResult DeleteJournalistConfirm(int id)
        {
            User s = _userService.GetJournalist(id);
            _userService.DeleteUser(s);
            return RedirectToAction("Index");
        }


        public ActionResult JournalistDetails(int id)
        {
            User s = _userService.GetJournalist(id);
            Account account = _accountService.GetAccountByJournalist(s.UserId);
            JournalistViewmodel journalist = new JournalistViewmodel();
            journalist.UserId = s.UserId;
            journalist.UserName = s.UserName;
            journalist.Email = s.Email;
            journalist.DateOfBirth = s.DateOfBirth;
            journalist.Gender = s.Gender;
            journalist.Role = s.Role;
            journalist.Phone = s.Phone;

            journalist.AccountName = account.AccountName;
            journalist.Password = account.Password;
            journalist.Active = account.Active;
            if (s == null)
                return HttpNotFound();
            return View(journalist);
        }
        [HttpPost]
        public JsonResult GetAllNews(int id)
        {

            var listNews = (from us in _userService.GetAll()
                            join acc in _accountService.GetAll() on us.UserId equals acc.UserId
                            join
        news in _newsService.GetAll() on acc.AccountName equals news.Journalist
                            where (us.UserId == id)
                            select new
                            {
                                newid = news.NewsId,
                                day = Convert.ToDateTime(news.PublicationDate),
                                image = news.Image,
                                title = news.Title,
                                active = news.Active,
                                description = news.Description

                            }).ToList();
            return Json(listNews, JsonRequestBehavior.AllowGet);
        }
    }
}

LaptrinhWWW_BaiTapLonWWW_Nhom08/UI.Web/Views/Journalist/AddJournalist.cshtml
@model UI.Web.Models.JournalistViewmodel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>JournalistViewmodel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.RadioButtonFor(model => model.Gender, 1, new { }) Nam
                @Html.RadioButtonFor(model => model.Gender, 2, new { }) Nữ
                @Html.RadioButtonFor(model => model.Gender, 3, new { }) Khác
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AccountName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AccountName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AccountName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Xác nhận mật khẩu", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

LaptrinhWWW_BaiTapLonWWW_Nhom08/UI.Web/Views/Journalist/DeleteJournalist.cshtml
@model EntityFrameworks.Model.User

<h3>Are you sure you want to delete this?</h3>
@using (Html.BeginForm("DeleteJournalistConfirm", "Journalist", new { id = Model.UserId }))
{
    <div>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.UserName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UserName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DateOfBirth)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DateOfBirth)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Gender)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Gender)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Role)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Role)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Phone)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Phone)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
}

LaptrinhWWW_BaiTapLonWWW_Nhom08/UI.Web/Views/Journalist/Edit.cshtml
@model EntityFrameworks.Model.User

@using (Html.BeginForm("Edit", "Journalist", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UserId)

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Role, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

LaptrinhWWW_BaiTapLonWWW_Nhom08/UI.Web/Views/Journalist/Index.cshtml
@model IEnumerable<EntityFrameworks.Model.User>

@if (UI.Web.Controllers.SharedController.Role == 3)
{
    <p>
        @Html.ActionLink("Create New", "AddJournalist")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfBirth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Role)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfBirth)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Gender)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Role)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Phone)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.UserId, @style = "color: #ff0000" }) |
                    @Html.ActionLink("Details", "JournalistDetails", new { id = item.UserId }) |
                    @Html.ActionLink("Delete", "DeleteJournalist", new { id = item.UserId })
                </td>
            </tr>
        }

    </table>
}
@if (UI.Web.Controllers.SharedController.Role == 2)
{
    <style>
        #customers {
            font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        #customers td, #customers th {
            border: 1px solid #ddd;
            padding: 8px;
        }

        #customers tr:nth-child(even) {
            background-color: #f2f2f2;
            width: 300px;
        }

        #customers tr:hover {
            background-color: #ddd;
        }

        #customers th {
            padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            background-color: #4CAF50;
            color: white;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="row d-flex justify-content-between">
                    <div class="col-lg-3 col-md-3">

                    </div>
                    <div class="col-lg-9 col-md-24">
                        <div class="properties__button">
                            <!--Nav Button  -->
                            <nav class="navbar navbar-expand-lg navbar-light bg-light">

                                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="true" aria-label="Toggle navigation">
                                    <span class="navbar-toggler-icon"></span>
                                </button>
                                <div class="navbar-collapse collapse show" id="navbarNavDropdown" style="">
                                    <ul class="navbar-nav">
                                        <li class="nav-item active">
                                            @*<a data-id="4" class="nav-link" href="#">Thêm bài báo<span class="sr-only">(current)</span></a>*@
                                        </li>
                                        <li class="nav-item">
                                            @*@Html.ActionLink("Click me", "GetAllNews", "Journalist", new { userID = 3 })*@

                                            <a data-id="4" class="nav-link" href="#"><span>Danh sách bài báo</span> </a>
                                        </li>
                                    
                                    </ul>
                                </div>
                            </nav>
                            <!--End Nav Button  -->
                        </div>
                        <div class="container">
                            <table id="customers">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th> Tiêu Đề Bài Báo</th>
                                        <th>Ngày Đăng</th>
                                        <th>Tình Trạng</th>
                                        <th>Chức năng</th>
                                    </tr>
                                </thead>
                                <tbody id="addNews">
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
  
}

LaptrinhWWW_BaiTapLonWWW_Nhom08/UI.Web/Views/Journalist/JournalistDetails.cshtml
@model UI.Web.Models.JournalistViewmodel

<div>
    <h4>JournalistViewmodel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @{
                if (Model.Gender == 1)
                {
                    Html.Label("Nam");
                }
                else if (Model.Gender == 2)
                {
                    Html.Label("Nữ");
                }
                else if (Model.Gender == 3)
                {
                    Html.Label("Khác");
                }
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccountName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccountName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new
    {@*userId = Model.UserId*@}) |
    @Html.ActionLink("Back to List", "Index")
</p>